#Allows for string replacment extensions.
[ext]
dir = "__root_dir__/sandbox" #gets the current dir of the module.toml
lwjgl_natives = "natives-__platform__" #gets the current dir of the module.toml
joml_version = "1.10.1"

#The root build structure for the module.
[main]
id = "sandbox"
version = "1.0.0-SNAPSHOT"
srcDirs = ["$dir/main/kotlin"]
resDirs = ["$dir/main/assets"]
entryPoint = "marx.MainKt"

[build]
#The repositories to be mapped to the module.
#By default this already includes mavenCentral.
repos = [
    "https://nexus.devsrsouza.com.br/repository/maven-public/"
]

#Imports local projects. Use urns here
modules = [
    "mod:engine/",
    "mod:window/",
]
#A platform is something that allows the speicfication of a single version number,
#thus allowing child jars to drop the version number off the end. They must match
#the group tag
platforms = [
    "org.lwjgl:lwjgl-bom:3.2.3"
]

implements = [
    "org.reflections:reflections:0.9.12",
    "com.google.guava:guava:30.1.1-jre",
    "org.lwjgl:lwjgl",
    "org.lwjgl:lwjgl-glfw",
    "org.lwjgl:lwjgl-opengl",
    "org.joml:joml:$joml_version",
    "com.dorkbox:MessageBus:2.4"
]



#The depencies that are to be sent to the runtime configuration. Useful for c++ binaries
runtimes = [
    "org.lwjgl:lwjgl::$lwjgl_natives",
    "org.lwjgl:lwjgl-glfw::$lwjgl_natives",
    "org.lwjgl:lwjgl-opengl::$lwjgl_natives",
]
