#Allows for string replacment extensions.
[ext]
dir = "__root_dir__/sandbox" #gets the current dir of the module.toml
lwjgl_natives = "natives-__platform__" #gets the current dir of the module.toml
joml_version = "1.10.1"
logger_version = "2.0.8"

#The root build structure for the module.
[main]
id = "sandbox"
version = "1.0.0-SNAPSHOT"
entryPoint = "marx.MainKt"

[build]
repos = ["$repos"]

# Here we can define the modules we wish to use. You're pretty much always
# going to want to have the engine, and the at the very least the window modules
modules = [
    "mod:engine/",
    "mod:window/",
    "mod:opengl/",
    "mod:editor/",
]

# This is imported from the engine's global extenisions.
platforms = ["$lwjgl_bom"]

# The are all of the the default depencies
implements = [
    "$lwjgl",
    "$guava",
    "$bus",
    "$logger",
    "$imgui"
]

#The depencies that are to be sent to the runtime configuration. Useful for c++ binaries
runtimes = ["$lwjgl_native", "$imgui_native"]


#This provides the directories for the main source set.
[build.main]
sources = ["$dir/main/kotlin"]
assets = ["$dir/main/assets"]

#This provides the directories for the test source set..
[build.test]
sources = ["$dir/test/kotlin"]
assets = ["$dir/test/assets"]