#Allows for string replacment extensions.
[ext]
dir = "__root_dir__/window" #gets the current dir of the module.toml

#The root build structure for the module.
[main]
id = "window"
version = "1.0.0-SNAPSHOT"

#Everything related to the build process goes here.
[build]
#The repositories to be mapped to the module.
#By default this already includes mavenCentral.
repos = ["$repos"]

#Imports local projects. Use urns here
modules = ["mod:engine/"]
#A platform is something that allows the speicfication of a single version number,
#thus allowing child jars to drop the version number off the end. They must match
#the group tag
platforms = ["$lwjgl_bom"]

implements = [
    "$lwjgl",
    "$guava",
    "$bus",
    "$logger"
]

#The depencies that are to be sent to the runtime configuration. Useful for c++ binaries
runtimes = [
    "$lwjgl_native"
]


#This provides the directories for the main source set.
[build.main]
sources = ["$dir/main/kotlin"]
assets = ["$dir/main/assets"]

#This provides the directories for the test source set..
[build.test]
sources = ["$dir/test/kotlin"]
assets = ["$dir/test/assets"]