#Allows for string replacment extensions.
[ext]
dir = "__root_dir__/window" #gets the current dir of the module.toml

#The root build structure for the module.
[main]
id = "window"
version = "1.0.0-SNAPSHOT"
srcDirs = ["$dir/main/kotlin"]
resDirs = ["$dir/main/assets"]
entryPoint = "marx.MainKt"

[build]
#The repositories to be mapped to the module.
#By default this already includes mavenCentral.
repos = [
    "https://nexus.devsrsouza.com.br/repository/maven-public/"
]

#Imports local projects. Use urns here
modules = [
    "mod:engine/",
]
#A platform is something that allows the speicfication of a single version number,
#thus allowing child jars to drop the version number off the end. They must match
#the group tag
platforms = [
    "$lwjgl_bom"
]

implements = [
    "$lwjgl",
    "$guava",
    "$bus",
    "$logger"
]

#The depencies that are to be sent to the runtime configuration. Useful for c++ binaries
runtimes = [
    "$lwjgl_native"
]